### ISSUE TITLE
lunatic::TcpListener accept() blocks ?

### ISSUE THREAD

**Issue by pinkforest** [lunatic-solutions/rust-lib#25]
```
$ lunatic --version
lunatic 0.9.0
$ grep lunatic < pywactor-backend/Cargo.toml 
lunatic = "0.9.1"
```

Is the lunatic::net::TcpListener::accept() supposed to block the runtime ?

My use-case is to bind() and listen() to multiple local addresses and tearing down/up served ip:ports dynamically

I was able to bind() and listen() to multiple addresses each done in init() under impl AbstractProcess for HttpServer

Problem however as soon as I put accept() into a loop where ever the whole runtime - not just the child - seems to hang on the first accept() call ?

I initially put the above directly into start() via fn init() but then I tried it separately in request() via handle()

```rust
impl ProcessRequest<HttpServerCommand> for HttpServer {
    type Response = u32;

    fn handle(state: &mut Self::State, _: HttpServerCommand) -> u32 {
        loop {
            if let Ok((tcp_stream, _peer)) = state.tcp_listener.accept() {
                let http = Http::start(tcp_stream, Some("hmmm"));
            }
	}
    }
}
```

repro:
```
git clone https://github.com/pinkforest/pywactor.git
cd pywactor/pywactor-backend
cargo run
```

The above should report Listen @ for both 9191 and 9192 ?
Connecting both 9191 and 9192 works but 9192 is not accepting connections in a way that I can't handle 9192
```
     Running `lunatic target/wasm32-wasi/debug/pywactor-backend.wasm`
Listening on addr: 127.0.0.1:9191
Listening on addr: 127.0.0.1:9192
handle() Listen @ 127.0.0.1:9191 
handle() Entered loop @ 127.0.0.1:9191
```

**Comment by pinkforest** [comment]
Minimal - Even if we try plainly directly via main() without AbstractProcess / Supervisor funsies

This is adapted [examples/tcp_echo_server.rs](https://github.com/lunatic-solutions/rust-lib/blob/main/examples/tcp_echo_server.rs) to adopt multiple listeners
```rust
use lunatic::{net, Mailbox, Process};
use std::io::{BufRead, BufReader, Write};

fn main() {
    let listener1 = net::TcpListener::bind("127.0.0.1:6666").unwrap();
    let listener2 = net::TcpListener::bind("127.0.0.1:6667").unwrap();
    println!("Listening 1 on addr: {}", listener1.local_addr().unwrap());
    println!("Listening 2 on addr: {}", listener2.local_addr().unwrap());

    loop {
        
        println!("Waiting on Listeners 1.. ");
        if let Ok((tcp_stream, _peer)) = listener1.accept() {
            // Pass the TCP stream as a context to the new process. We can't use a closures that
            // capture parent variables because no memory is shared between processes.
            println!("Listener1 Accepted()");
            Process::spawn(tcp_stream, handle);
        }

        println!("Waiting on Listeners 2.. ");
        if let Ok((tcp_stream, _peer)) = listener2.accept() {
            // Pass the TCP stream as a context to the new process. We can't use a closures that
            // capture parent variables because no memory is shared between processes.
            println!("Listener2 Accepted()");
            Process::spawn(tcp_stream, handle);
        }
    }
}

fn handle(mut tcp_stream: net::TcpStream, _: Mailbox<()>) {
    let mut buf_reader = BufReader::new(tcp_stream.clone());
    loop {
        let mut buffer = String::new();
        let read = buf_reader.read_line(&mut buffer).unwrap();
        if buffer.contains("exit") || read == 0 {
            return;
        }
        tcp_stream.write(buffer.as_bytes()).unwrap();
    }
}
```

Results predictably only 6666 accepting connections whilst 6667 is zombie accepts (kernel) but doesn't get read in runtime
```
     Running `lunatic target/wasm32-wasi/debug/minimalist-block.wasm`
Listening 1 on addr: 127.0.0.1:6666
Listening 2 on addr: 127.0.0.1:6667
Waiting on Listeners 1.. 
```

**Comment by bkolobara** [comment]
Yes, `TcpListener::accept()` must block. The call to it will return a `TcpStream`, so it blocks until a `TcpStream` is available.

What you want is to concurrently listen on multiple ports in different processes, but you can't use `AbstractProcesses` for it. `AbstractProcesses` will handle incoming messages in the `handle` methods sequentially. This means if you have an infinite loop inside of the `handle` message, no other message will be handled because the handling of this one never finishes.

If you add a `spawn_link!` to your example:

```rust
impl ProcessRequest<HttpServerCommand> for HttpServer {
    type Response = u32;

    fn handle(state: &mut Self::State, _: HttpServerCommand) -> u32 {
        let _ = spawn_link!(|| {
            loop {
                if let Ok((tcp_stream, _peer)) = state.tcp_listener.accept() {
                    let http = Http::start(tcp_stream, Some("hmmm"));
                }
	    }
        });
    }
}
```

This means that every time the `HttpServer` receives a `HttpServerCommand` it will start a linked sub-process that concurrently listens to new incoming connections.

`AbstractProcesses` are meant for specific use-cases where you have a process that handles incoming messages in an elegant way. If you are dealing with networking, you are better of just using processes spawned from a function.

**Comment by pinkforest** [comment]
Cool. I was wondering why vanilla spawn_link! worked - thanks for the explanation. I will send a PR around documenting it and maybe example to do multiple listen's

**Comment by pinkforest** [comment]
Done 
- [x] #26
- [x] #27
